//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guitar.WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternetLink
    {
        public int linkID { get; set; }
        public string linkName { get; set; }
        public int songID { get; set; }
        public bool isTab { get; set; }
        public bool isTutorial { get; set; }
        public bool isCover { get; set; }
        public string linkAdress { get; set; }
    
        public virtual Song Song { get; set; }
    }
}
